"""Deprecated: use ``src.engine.layout.golden``. Thin re-export."""
from __future__ import annotations

from src.engine.layout.golden import *  # noqa: F403
from src.engine.layout.golden import (
    EDITOR_FLOOR_2X2_ORIENTATION_REFERENCE,
    EDITOR_FLOOR_5X5_TILE_LAYOUT_ROW_WIDTHS,
    EDITOR_FLOOR_5X5_TILE_LAYOUT_SKETCH,
    EDITOR_FLOOR_5X5_TILE_CANVAS_VIEW,
    EDITOR_FLOOR_5X5_TILE_REFERENCE,
    build_alphabet_floor_by_char,
    rasterize_packed_draw_map_to_canvas,
    tile_alphabet_letter,
    PACKED_LAYOUT_FEET_COL,
    PACKED_LAYOUT_FEET_ROW,
    STAMP_CELL_ORDER,
    TILE_SLOT_DISPLAY,
    TILE_SLOT_VIEW,
    TILE_VIEW_CANVAS_H,
    TILE_VIEW_CANVAS_W,
    assert_packed_test_floor_matches_reference,
    assert_test_tile_view_matches_reference,
    compute_orientation_slot_view,
    compute_tile_slot_view,
    is_tile_quad_canonical,
    iter_floor_tile_view_pair_cols,
    layout_sketch_row_widths,
    packed_canvas_dimensions,
    packed_layout_screen_offset,
    packed_layout_silhouette,
    render_orientation_packed_sketch,
    render_packed_test_floor,
    tile_orientation_quad,
    validate_all_tile_quads,
    validate_tile_quad,
    visible_orientation_glyphs,
)
